apiVersion: apps/v1

kind: Deployment

metadata:
  name: new-deployemnt

  labels:
    app: server

spec:
  replicas: 2

  selector:
    matchLabels:
      app: server

  template:
    metadata:
      labels:
        app: server

    spec:
      containers:
        - name: express-server
          image: node_app
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
